### ISSUE TITLE
New issue!

### ISSUE THREAD

**Issue by hosaka** [ty33/hello-world#2]
A common workflow, is someone comes around and says: "I think there's an issue in Readme file", which is not covered by issue #1. (you can literally type #<number> and it will pick up the number of the issue/pull request you're referring to).

I propose a particular change to the readme file and will be opening a pull request to it soon for owners review.

A pull request is basically someone suggesting their edits to your repository. You can review it, ask the contributor to amend it until you're satisfied with the changes, and then merge it into your repository. Or if someone being silly and suggesting rubbish, just decline the change. I'll open a pull request in a moment.

**Comment by ty33** [comment]
hehe, well I'm tying to create a pull request for my branch and I can't find the pull request in the sidebar (or find the sidebar) :|

**Comment by hosaka** [comment]
Oh yeah...very recently the sidebar moved to the top. So you have tabs up top now. "Code", "Issues", "Pull Requests"

**Comment by ty33** [comment]
done, but I think I could've done a better job of reviewing. I need to figure out how to look and diffs and stuff.

**Comment by hosaka** [comment]
Yeah, via github is fairly easy for viewing diffs. On the command line "git diff" or "git difftool" for an external tool of your choice :)
